import Foundation

enum SeedData {
    static let recipes: [Recipe] = [
        Recipe(
            id: "r1",
            title: "Lemon Herb Chicken Bowls",
            cuisine: "Mediterranean",
            img: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
            source: "Website", prep: 15, cook: 22, servings: 4, cal: 520,
            macros: Macros(protein: 38, carbs: 42, fat: 19),
            tags: ["High protein", "Meal prep"], favorite: true,
            ingredients: [
                Ingredient(name: "Chicken thighs", qty: "600 g", category: "Meat"),
                Ingredient(name: "Lemon", qty: "2", category: "Produce"),
                Ingredient(name: "Olive oil", qty: "3 tbsp", category: "Pantry"),
                Ingredient(name: "Parsley", qty: "1 bunch", category: "Produce"),
                Ingredient(name: "Couscous", qty: "250 g", category: "Pantry"),
                Ingredient(name: "Cherry tomatoes", qty: "200 g", category: "Produce"),
                Ingredient(name: "Feta", qty: "100 g", category: "Dairy"),
            ],
            steps: [
                "Whisk lemon juice, olive oil, parsley, salt, and pepper into a marinade.",
                "Coat the chicken thighs and rest for 10 minutes.",
                "Sear chicken over medium-high heat, 6–7 minutes per side, until cooked through.",
                "Steam the couscous and fluff with a fork.",
                "Slice chicken, assemble bowls with couscous, tomatoes, and feta.",
                "Finish with extra lemon and parsley.",
            ],
            notes: "Great cold the next day."
        ),
        Recipe(
            id: "r2",
            title: "Creamy Tuscan Salmon",
            cuisine: "Italian",
            img: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80",
            source: "YouTube", prep: 10, cook: 18, servings: 2, cal: 610,
            macros: Macros(protein: 41, carbs: 12, fat: 44),
            tags: ["Low carb", "Dinner"], favorite: true,
            ingredients: [
                Ingredient(name: "Salmon fillets", qty: "2", category: "Seafood"),
                Ingredient(name: "Heavy cream", qty: "200 ml", category: "Dairy"),
                Ingredient(name: "Sun-dried tomatoes", qty: "80 g", category: "Pantry"),
                Ingredient(name: "Baby spinach", qty: "120 g", category: "Produce"),
                Ingredient(name: "Garlic", qty: "3 cloves", category: "Produce"),
                Ingredient(name: "Parmesan", qty: "40 g", category: "Dairy"),
            ],
            steps: [
                "Pat salmon dry and season both sides.",
                "Sear skin-side down 4 minutes, flip for 2, then set aside.",
                "Soften garlic and sun-dried tomatoes in the same pan.",
                "Pour in cream, simmer, and stir in parmesan.",
                "Wilt the spinach into the sauce.",
                "Return salmon and spoon sauce over to finish.",
            ],
            notes: ""
        ),
        Recipe(
            id: "r3",
            title: "Spicy Peanut Noodles",
            cuisine: "Thai",
            img: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&q=80",
            source: "Pasted text", prep: 12, cook: 8, servings: 3, cal: 480,
            macros: Macros(protein: 16, carbs: 62, fat: 20),
            tags: ["Vegetarian", "Quick"], favorite: false,
            ingredients: [
                Ingredient(name: "Rice noodles", qty: "300 g", category: "Pantry"),
                Ingredient(name: "Peanut butter", qty: "4 tbsp", category: "Pantry"),
                Ingredient(name: "Soy sauce", qty: "3 tbsp", category: "Pantry"),
                Ingredient(name: "Lime", qty: "1", category: "Produce"),
                Ingredient(name: "Scallions", qty: "4", category: "Produce"),
                Ingredient(name: "Chili crisp", qty: "2 tsp", category: "Pantry"),
            ],
            steps: [
                "Soak rice noodles in hot water until just tender.",
                "Whisk peanut butter, soy, lime juice, and a splash of hot water into a sauce.",
                "Toss noodles through the sauce over low heat.",
                "Top with scallions and chili crisp.",
            ],
            notes: "Add shredded chicken for protein."
        ),
        Recipe(
            id: "r4",
            title: "Overnight Oats with Berries",
            cuisine: "Breakfast",
            img: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=800&q=80",
            source: "Website", prep: 5, cook: 0, servings: 1, cal: 340,
            macros: Macros(protein: 14, carbs: 52, fat: 9),
            tags: ["Breakfast", "Make ahead"], favorite: false,
            ingredients: [
                Ingredient(name: "Rolled oats", qty: "60 g", category: "Pantry"),
                Ingredient(name: "Greek yogurt", qty: "100 g", category: "Dairy"),
                Ingredient(name: "Milk", qty: "120 ml", category: "Dairy"),
                Ingredient(name: "Mixed berries", qty: "80 g", category: "Produce"),
                Ingredient(name: "Honey", qty: "1 tbsp", category: "Pantry"),
                Ingredient(name: "Chia seeds", qty: "1 tsp", category: "Pantry"),
            ],
            steps: [
                "Stir oats, yogurt, milk, chia, and honey in a jar.",
                "Refrigerate overnight, at least 6 hours.",
                "Top with berries before serving.",
            ],
            notes: ""
        ),
        Recipe(
            id: "r5",
            title: "Beef Suya Skewers",
            cuisine: "West African",
            img: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
            source: "Scan", prep: 20, cook: 12, servings: 4, cal: 450,
            macros: Macros(protein: 36, carbs: 8, fat: 30),
            tags: ["Grill", "Spicy"], favorite: false,
            ingredients: [
                Ingredient(name: "Beef sirloin", qty: "700 g", category: "Meat"),
                Ingredient(name: "Roasted peanuts", qty: "80 g", category: "Pantry"),
                Ingredient(name: "Paprika", qty: "2 tsp", category: "Spices"),
                Ingredient(name: "Cayenne", qty: "1 tsp", category: "Spices"),
                Ingredient(name: "Ginger powder", qty: "1 tsp", category: "Spices"),
                Ingredient(name: "Red onion", qty: "1", category: "Produce"),
            ],
            steps: [
                "Grind peanuts with paprika, cayenne, ginger, and salt into suya spice.",
                "Slice beef thinly and thread onto skewers.",
                "Oil lightly and press the spice mix onto the meat.",
                "Grill over high heat, 5–6 minutes per side.",
                "Serve with sliced onion and extra spice.",
            ],
            notes: "Rest the skewers 5 minutes before serving."
        ),
        Recipe(
            id: "r6",
            title: "Shakshuka",
            cuisine: "Middle Eastern",
            img: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80",
            source: "Scan", prep: 10, cook: 20, servings: 2, cal: 380,
            macros: Macros(protein: 19, carbs: 24, fat: 24),
            tags: ["Vegetarian", "Brunch"], favorite: false,
            ingredients: [
                Ingredient(name: "Eggs", qty: "4", category: "Dairy"),
                Ingredient(name: "Crushed tomatoes", qty: "400 g", category: "Pantry"),
                Ingredient(name: "Red bell pepper", qty: "1", category: "Produce"),
                Ingredient(name: "Onion", qty: "1", category: "Produce"),
                Ingredient(name: "Cumin", qty: "1 tsp", category: "Spices"),
                Ingredient(name: "Feta", qty: "60 g", category: "Dairy"),
            ],
            steps: [
                "Soften onion and pepper in olive oil.",
                "Add cumin, then crushed tomatoes; simmer 10 minutes.",
                "Make wells and crack in the eggs.",
                "Cover and cook until whites are set.",
                "Crumble feta over and serve with bread.",
            ],
            notes: ""
        ),
        Recipe(
            id: "r7",
            title: "Garlic Butter Shrimp Pasta",
            cuisine: "Italian",
            img: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&q=80",
            source: "Website", prep: 10, cook: 15, servings: 3, cal: 560,
            macros: Macros(protein: 32, carbs: 58, fat: 22),
            tags: ["Quick", "Dinner"], favorite: false,
            ingredients: [
                Ingredient(name: "Shrimp", qty: "400 g", category: "Seafood"),
                Ingredient(name: "Linguine", qty: "300 g", category: "Pantry"),
                Ingredient(name: "Butter", qty: "60 g", category: "Dairy"),
                Ingredient(name: "Garlic", qty: "4 cloves", category: "Produce"),
                Ingredient(name: "Lemon", qty: "1", category: "Produce"),
                Ingredient(name: "Parsley", qty: "1 handful", category: "Produce"),
            ],
            steps: [
                "Boil linguine until al dente; reserve a cup of pasta water.",
                "Melt butter and soften the garlic gently.",
                "Add shrimp and cook until just pink.",
                "Toss pasta through with lemon juice and pasta water.",
                "Finish with parsley and black pepper.",
            ],
            notes: ""
        ),
        Recipe(
            id: "r8",
            title: "Salmon Rice Bowl",
            cuisine: "Japanese",
            img: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
            source: "Food scan match", prep: 15, cook: 18, servings: 2, cal: 590,
            macros: Macros(protein: 34, carbs: 66, fat: 21),
            tags: ["High protein", "Fresh"], favorite: false,
            ingredients: [
                Ingredient(name: "Salmon fillets", qty: "2", category: "Seafood"),
                Ingredient(name: "Cooked rice", qty: "300 g", category: "Pantry"),
                Ingredient(name: "Cucumber", qty: "1", category: "Produce"),
                Ingredient(name: "Avocado", qty: "1", category: "Produce"),
                Ingredient(name: "Baby spinach", qty: "60 g", category: "Produce"),
                Ingredient(name: "Sesame seeds", qty: "2 tsp", category: "Pantry"),
                Ingredient(name: "Soy sauce", qty: "2 tbsp", category: "Pantry"),
                Ingredient(name: "Lime", qty: "1", category: "Produce"),
            ],
            steps: [
                "Season salmon with salt, pepper, and a little soy sauce.",
                "Sear salmon over medium heat for 3-4 minutes per side until just cooked.",
                "Slice cucumber and avocado while the rice warms.",
                "Fluff rice into bowls and top with spinach, cucumber, avocado, and salmon.",
                "Finish with sesame seeds, lime juice, and extra soy sauce.",
            ],
            notes: "Use leftover rice to make this faster."
        ),
    ]
}
