#!/usr/bin/env bash
# goodiesSnap AI gateway — run once on the VPS as root.
#
# Puts Caddy in front of the local Ollama so apps can reach it at https://ai.goodiessnap.com.
# Ollama itself stays bound to 127.0.0.1; Caddy is the only thing listening publicly, it gets
# a Let's Encrypt certificate automatically, and it refuses any request without a valid app
# key. Only inference endpoints are forwarded — model management (/api/pull, /api/delete,
# /api/create, ...) is never reachable from outside.
#
# Safe to re-run: existing app keys are kept, config is rewritten, services are reloaded.
#
#   bash setup-ai-gateway.sh                 # set up / refresh
#   bash setup-ai-gateway.sh --add-app NAME  # mint a key for another app, then refresh
#   bash setup-ai-gateway.sh --rotate NAME   # replace one app's key, then refresh
set -euo pipefail

DOMAIN="${DOMAIN:-ai.goodiessnap.com}"
CHAT_MODEL="${CHAT_MODEL:-qwen2.5:3b}"
EMBED_MODEL="${EMBED_MODEL:-nomic-embed-text}"
KEY_DIR=/etc/caddy/app-keys

[ "$(id -u)" -eq 0 ] || { echo "Run as root."; exit 1; }
command -v ollama >/dev/null || { echo "Ollama is not installed."; exit 1; }

mint_key() { # $1 = app name
  local name="$1"
  [[ "$name" =~ ^[a-z0-9-]{2,32}$ ]] || { echo "App name must be 2-32 chars of a-z, 0-9, -"; exit 1; }
  umask 077
  echo "gsk_${name}_$(openssl rand -hex 24)" > "$KEY_DIR/$name"
  echo "Key for '$name' written to $KEY_DIR/$name"
}

mkdir -p "$KEY_DIR"
chmod 700 "$KEY_DIR"

case "${1:-}" in
  --add-app) [ -n "${2:-}" ] || { echo "Usage: --add-app NAME"; exit 1; }
             [ -f "$KEY_DIR/$2" ] && { echo "'$2' already has a key; use --rotate."; exit 1; }
             mint_key "$2" ;;
  --rotate)  [ -f "$KEY_DIR/${2:-}" ] || { echo "No such app: ${2:-}"; exit 1; }
             mint_key "$2" ;;
  "")        ;;
  *)         echo "Unknown option $1"; exit 1 ;;
esac

# First run: goodiessnap is the first app.
[ -f "$KEY_DIR/goodiessnap" ] || mint_key goodiessnap

echo "==> Tuning Ollama (loopback only, model always loaded, 2 chats at once)"
mkdir -p /etc/systemd/system/ollama.service.d
cat > /etc/systemd/system/ollama.service.d/goodiessnap.conf <<'EOF'
[Service]
Environment="OLLAMA_HOST=127.0.0.1:11434"
Environment="OLLAMA_KEEP_ALIVE=-1"
Environment="OLLAMA_NUM_PARALLEL=2"
Environment="OLLAMA_MAX_LOADED_MODELS=2"
Environment="OLLAMA_MAX_QUEUE=16"
EOF
systemctl daemon-reload
systemctl restart ollama
for _ in $(seq 1 30); do curl -sf http://127.0.0.1:11434/api/version >/dev/null && break; sleep 1; done

echo "==> Pulling models ($CHAT_MODEL, $EMBED_MODEL)"
ollama pull "$CHAT_MODEL"
ollama pull "$EMBED_MODEL"

if ! command -v caddy >/dev/null; then
  echo "==> Installing Caddy"
  apt-get update -q
  apt-get install -y -q debian-keyring debian-archive-keyring apt-transport-https curl gnupg
  curl -1sLf https://dl.cloudsmith.io/public/caddy/stable/gpg.key \
    | gpg --dearmor --yes -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt \
    > /etc/apt/sources.list.d/caddy-stable.list
  chmod o+r /usr/share/keyrings/caddy-stable-archive-keyring.gpg /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -q
  apt-get install -y -q caddy
fi

echo "==> Writing Caddy config for $DOMAIN"
KEY_LINES=""
for f in "$KEY_DIR"/*; do KEY_LINES+=$'\t\t\theader Authorization "Bearer '"$(cat "$f")"$'"\n'; done

cat > /etc/caddy/Caddyfile <<EOF
# Generated by setup-ai-gateway.sh — edit the script, not this file.
$DOMAIN {
	request_body {
		max_size 1MB
	}

	# Every request must carry one of the app keys.
	@nokey {
		not {
$KEY_LINES		}
	}
	# Inference only. Model management stays local.
	@inference path /api/chat /api/generate /api/embed /api/embeddings /api/tags /api/ps /api/version /v1/chat/completions /v1/embeddings /v1/models

	# route keeps these in the order written; Caddy would otherwise run the proxy
	# before the key check.
	route {
		respond @nokey \`{"error":"unauthorized"}\` 401
		reverse_proxy @inference 127.0.0.1:11434 {
			header_up Host 127.0.0.1:11434
			header_up -Authorization
			flush_interval -1
			transport http {
				response_header_timeout 5m
			}
		}
		respond \`{"error":"not_found"}\` 404
	}

	log {
		output file /var/log/caddy/ai-access.log {
			roll_size 20MiB
			roll_keep 5
		}
		format filter {
			wrap json
			fields {
				request>headers>Authorization delete
			}
		}
	}
}
EOF
chown root:caddy /etc/caddy/Caddyfile
chmod 640 /etc/caddy/Caddyfile
mkdir -p /var/log/caddy && chown caddy:caddy /var/log/caddy

caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile
# validate runs as root and opens the log file, leaving it root-owned; the caddy service
# user then can't write it and refuses to start.
chown -R caddy:caddy /var/log/caddy
systemctl enable caddy >/dev/null
systemctl reload caddy 2>/dev/null || systemctl restart caddy

echo "==> Warming $CHAT_MODEL"
curl -s http://127.0.0.1:11434/api/generate \
  -d "{\"model\":\"$CHAT_MODEL\",\"prompt\":\"hi\",\"stream\":false,\"options\":{\"num_predict\":1}}" >/dev/null || true

echo "==> Checking https://$DOMAIN (certificate can take up to a minute on first run)"
KEY="$(cat "$KEY_DIR/goodiessnap")"
ok=""
for _ in $(seq 1 12); do
  code=$(curl -s -o /dev/null -w '%{http_code}' -H "Authorization: Bearer $KEY" "https://$DOMAIN/api/version" || true)
  [ "$code" = "200" ] && { ok=1; break; }
  sleep 5
done
nokey=$(curl -s -o /dev/null -w '%{http_code}' "https://$DOMAIN/api/version" || true)

echo
if [ -n "$ok" ] && [ "$nokey" = "401" ]; then
  echo "SUCCESS: gateway is live. With key -> 200, without key -> 401."
else
  echo "Gateway not reachable yet (with key: ${code:-none}, without: $nokey)."
  echo "Check that ports 80 and 443 are open and that $DOMAIN points to this server,"
  echo "then run: journalctl -u caddy --no-pager -n 50"
fi
echo
echo "App keys (put each one in that app's backend secrets as OLLAMA_API_KEY):"
for f in "$KEY_DIR"/*; do echo "  $(basename "$f"): $(cat "$f")"; done
