#!/usr/bin/env bash
# FreeLLMAPI on the VPS — run as root. Safe to re-run (keeps keys, account and data).
#
# FreeLLMAPI (github.com/tashfeenahmed/freellmapi) routes OpenAI-compatible requests across the
# free tiers of many LLM providers, plus this server's own Ollama. Its docs say it is
# single-user and must not face the internet directly, so:
#   - the container uses the host network but listens on 127.0.0.1:3001 only;
#   - Caddy (already running for ai.goodiessnap.com) is the only public door, with HTTPS;
#   - the dashboard account is created from config before the listener starts, so the
#     unauthenticated first-run setup page never exists.
# It reaches Ollama directly on 127.0.0.1:11434 — no gateway key involved.
#
#   bash setup-freellmapi.sh
#   DOMAIN=llm.example.com ADMIN_EMAIL=me@example.com bash setup-freellmapi.sh
set -euo pipefail

DOMAIN="${DOMAIN:-srv1322523.hstgr.cloud}"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@goodiessnap.com}"
DIR=/opt/freellmapi
IMAGE=ghcr.io/tashfeenahmed/freellmapi:latest
PORT=3001

[ "$(id -u)" -eq 0 ] || { echo "Run as root."; exit 1; }
command -v caddy >/dev/null || { echo "Caddy is missing — run setup-ai-gateway.sh first."; exit 1; }

if ! command -v docker >/dev/null; then
  echo "==> Installing Docker"
  curl -fsSL https://get.docker.com | sh
fi
docker compose version >/dev/null

mkdir -p "$DIR"
chmod 700 "$DIR"
cd "$DIR"

if [ ! -f .env ]; then
  echo "==> Generating encryption key"
  umask 077
  cat > .env <<EOF
ENCRYPTION_KEY=$(openssl rand -hex 32)
PORT=$PORT
HOST=127.0.0.1
TRUST_PROXY=1
NODE_ENV=production
FREEAPI_CONFIG_PATH=/config/freellmapi.config.json
EOF
fi

# First run only: the admin account and the local Ollama provider. On later runs the admin
# entry is ignored by FreeLLMAPI (an account already exists), so the file is left alone.
if [ ! -f freellmapi.config.json ]; then
  echo "==> Creating dashboard account for $ADMIN_EMAIL"
  umask 077
  openssl rand -base64 24 | tr -d '/+=' | cut -c1-20 > admin-password
  cat > freellmapi.config.json <<EOF
{
  "admin": { "email": "$ADMIN_EMAIL", "password": "$(cat admin-password)" },
  "customProviders": [
    {
      "baseUrl": "http://127.0.0.1:11434/v1",
      "label": "VPS Ollama",
      "models": [
        { "model": "qwen2.5:3b", "displayName": "Qwen 2.5 3B (this VPS)" }
      ]
    }
  ],
  "routing": { "strategy": "balanced" }
}
EOF
fi

# The image drops to its `node` user (uid 1000) before reading the config, so that user
# must own it; mode 600 keeps it private from everyone else on the host.
chown 1000:1000 freellmapi.config.json
chmod 600 freellmapi.config.json

cat > docker-compose.yml <<EOF
# Generated by setup-freellmapi.sh
services:
  freellmapi:
    image: $IMAGE
    # Host network so it can reach Ollama on 127.0.0.1; HOST=127.0.0.1 in .env keeps the
    # listener private. Caddy is the only thing that talks to it.
    network_mode: host
    env_file: .env
    volumes:
      - freellmapi-data:/app/server/data
      - ./freellmapi.config.json:/config/freellmapi.config.json:ro
    restart: unless-stopped
volumes:
  freellmapi-data:
EOF

echo "==> Starting FreeLLMAPI"
docker compose pull -q
# Recreate so a fixed config or env is always picked up, even from a crash-looping container.
docker compose up -d --force-recreate

ok=""
for _ in $(seq 1 30); do
  curl -sf "http://127.0.0.1:$PORT/api/ping" >/dev/null && { ok=1; break; }
  sleep 2
done
[ -n "$ok" ] || { echo "FreeLLMAPI did not start. Latest logs:"; docker compose logs --tail 15; exit 1; }

# Make sure the listener really is private before publishing anything.
if ss -tlnH "sport = :$PORT" | awk '{print $4}' | grep -qv '^127\.0\.0\.1:'; then
  echo "Refusing to continue: port $PORT is listening beyond 127.0.0.1."
  ss -tln "sport = :$PORT"; exit 1
fi

echo "==> Publishing https://$DOMAIN through Caddy"
mkdir -p /etc/caddy/sites /var/log/caddy
cat > /etc/caddy/sites/freellmapi.caddy <<EOF
# Generated by setup-freellmapi.sh
$DOMAIN {
	encode gzip
	reverse_proxy 127.0.0.1:$PORT {
		flush_interval -1
		transport http {
			response_header_timeout 10m
		}
	}
	log {
		output file /var/log/caddy/freellmapi-access.log {
			roll_size 20MiB
			roll_keep 5
		}
		format filter {
			wrap json
			fields {
				request>headers>Authorization delete
				request>headers>Cookie delete
			}
		}
	}
}
EOF
grep -q '^import /etc/caddy/sites/\*.caddy' /etc/caddy/Caddyfile ||
  printf '\n# Other sites on this server (one file each)\nimport /etc/caddy/sites/*.caddy\n' >> /etc/caddy/Caddyfile
caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile
chown -R caddy:caddy /var/log/caddy
systemctl reload caddy

echo "==> Checking https://$DOMAIN (certificate can take up to a minute)"
code=""
for _ in $(seq 1 12); do
  code=$(curl -s -o /dev/null -w '%{http_code}' "https://$DOMAIN/api/ping" || true)
  [ "$code" = "200" ] && break
  sleep 5
done

echo
if [ "$code" = "200" ]; then
  echo "SUCCESS: FreeLLMAPI is live at https://$DOMAIN"
else
  echo "Not reachable yet over HTTPS (got ${code:-none}). Check: journalctl -u caddy --no-pager -n 30"
fi
echo
echo "Dashboard login:  $ADMIN_EMAIL"
if [ -f admin-password ]; then
  echo "Password:         $(cat admin-password)"
  echo "(Save it somewhere private. It is also in $DIR/admin-password, readable by root only.)"
fi
echo
echo "Next: sign in, add free provider keys on the Keys page, and copy your unified"
echo "'freellmapi-…' API key from that page for your apps."
